cc_library(
        name = "pi",
        srcs = glob(
                [ "src/*.cc",
                  "src/*.h" ],
                ),
        hdrs = glob(
                ["include/*.h"],
                ),
        includes = ["include"],
        visibility = ["//visibility:public"],
    )

