# create config settings based on bazel provided platform values
config_setting(
    name = "osx",
    values = { "cpu": "darwin" },
    visibility = ["//visibility:public"],
)
config_setting(
    name = "linux",
    values = { "cpu": "k8" },
    visibility = ["//visibility:public"],
)

